export const PACKAGES = {
  PREMIUM: "PREMIUM_PLAN",
  PROBLEM: "PROBLEM_PLAN",
  COURSE: "COURSE_PLAN",
  FREE: "FREE_PLAN"
};

export const DURATION = {
  MONTHLY: "MONTHLY_PACKAGE",
  YEARLY: "YEARLY_PACKAGE"
};
