export const NotificationRedirectTypes = {
  PROBLEM_COMMENT: "PROBLEM_COMMENT",
  SOLVED_PROBLEM: "SOLVED_PROBLEM",
  COURSE_REVIEW: "COURSE_REVIEW",
  COURSE_COMMENT: "COURSE_COMMENT",
  COURSE_COMPLETE: "COURSE_COMPLETE"
};
